version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
    - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
    - 9092:9092
    depends_on:
    - zookeeper
    links:
    - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  consumer:
    image: consumer
    container_name: consumer
    depends_on:
    - kafka
    restart: always
    ports:
    - 8084:8080
    links:
    - kafka:kafka
    - mongocontainer

  producer:
    image: producer
    container_name: producer
    restart: always
    ports:
    - 8085:8080
    depends_on:
    - kafka
    links:
    - kafka:kafka
    - mongocontainer

  mongocontainer:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - ~/mongo-data:/data/db
